language: go

go:
  - 1.8.x
  - 1.9.x

before_install:
  - go get -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
